http://www.asterisk.org/

使用chrome录音
http://www.cnblogs.com/blqw/p/3782420.html

sip client
https://www.doubango.org/sipml5/

sip运营商

https://voip.ms/

voip 使用指导
http://blog.sina.com.cn/s/blog_53ed87c10101iloi.html

X-lite



将Asterisk联入真实世界(PSTN)需要了解的
http://bbs.voip88.com/thread-302-1-1.html
通信社区
http://bbs.voip88.com/

北恩话机api
http://download.csdn.net/download/mr_rain/8443527

hwcloudos@163.com
